########################################################################################################################
# Memo:
########################################################################################################################

# This file is used to configure files/folders to copy and folder links to create (before running premake).

# Mappings ($ string substitutions). Name and examples:
# |==========================================================
# | $platform      | 'windows-x86_64'     | 'linux-x86_64'  |
# |----------------------------------------------------------
# | $lib_ext       | '.dll'               | '.so'           |
# | $lib_prefix    | ''                   | 'lib.'          |
# | $bindings_ext  | '.pyd'               | '.so'           |
# | $exe_ext       | '.exe'               | ''              |
# | $shell_ext     | '.bat'               | '.sh'           |
# |==========================================================
#
# |==========================================================
# | $config        | 'debug'              | 'release'       |
# |==========================================================

# Filters. For example, debug config on linux-x86_64 matches all those toml keys:
# [linux-x86_64]
# [debug]
# [linux.debug]
# So you can use those in any order as a keys: ["linux-x86_64", "debug", "linux", "x86_64"]


########################################################################################################################
# NOTE:
# This file is almost empty, we prefer to use the second one: _build/generated/prebuild.toml. It is generated by premake
# configurations. That allows to keep all copy and link configuration together with other project data.
########################################################################################################################


########################################################################################################################
# Common section:
########################################################################################################################

copy = [
    ["_build/intermediate/sdk-runtime/$config/config", "_build/$platform/$config/config"],
    ["_build/intermediate/sdk-runtime/$config/plugins", "_build/$platform/$config/plugins"],
    ["_build/intermediate/sdk-runtime/$config/python", "_build/$platform/$config/python"],
    ["_build/intermediate/sdk-runtime/$config/lib/**", "_build/$platform/$config"], # remap libs & usd plugins to root of build

    # extras not installed by connect-sdk installer
    ["_build/target-deps/usd/$config/bin/${lib_prefix}MaterialXCore*${lib_ext}*", "_build/$platform/$config"],
    ["_build/target-deps/usd/$config/lib/${lib_prefix}MaterialXCore*${lib_ext}*", "_build/$platform/$config"],
    ["_build/target-deps/usd/$config/bin/${lib_prefix}MaterialXFormat*${lib_ext}*", "_build/$platform/$config"],
    ["_build/target-deps/usd/$config/lib/${lib_prefix}MaterialXFormat*${lib_ext}*", "_build/$platform/$config"],
    ["_build/target-deps/usd/$config/lib/${lib_prefix}*usdHydra${lib_ext}", "_build/$platform/$config"],
    ["_build/target-deps/usd/$config/lib/${lib_prefix}*usdMtlx${lib_ext}", "_build/$platform/$config"],
    ["_build/target-deps/usd/$config/lib/${lib_prefix}*usdPhysics${lib_ext}", "_build/$platform/$config"],
    ["_build/target-deps/usd/$config/lib/${lib_prefix}*usdSkel${lib_ext}", "_build/$platform/$config"],
    ["_build/target-deps/usd/$config/lib/${lib_prefix}*usdUI${lib_ext}", "_build/$platform/$config"],
    ["_build/target-deps/usd/$config/lib/python/pxr/UsdHydra", "_build/$platform/$config/python/pxr/UsdHydra"],
    ["_build/target-deps/usd/$config/lib/python/pxr/UsdMtlx", "_build/$platform/$config/python/pxr/UsdMtlx"],
    ["_build/target-deps/usd/$config/lib/python/pxr/UsdPhysics", "_build/$platform/$config/python/pxr/UsdPhysics"],
    ["_build/target-deps/usd/$config/lib/python/pxr/UsdSkel", "_build/$platform/$config/python/pxr/UsdSkel"],
    ["_build/target-deps/usd/$config/lib/python/pxr/UsdUI", "_build/$platform/$config/python/pxr/UsdUI"],

    ["_build/target-deps/omni_transcoding/$config/python", "_build/$platform/$config/python"],

    ["_build/target-deps/omni_asset_validator/$config/**/*.*", "_build/$platform/$config"],
    # used only when source linking for local development of asset validator
    ["_build/target-deps/omni_asset_validator/omni", "_build/$platform/$config/python/omni"],
    ["_build/target-deps/omni_asset_validator/pip_prebundle/**/*.*", "_build/$platform/$config/python"],
    ["_build/target-deps/omni_asset_validator/scripts", "_build/$platform/$config/scripts"],
]
link = [
    ["_build/target-deps/python", "_build/$platform/$config/python-runtime"],
]

########################################################################################################################
# Windows platform:
########################################################################################################################

[windows-x86_64]
copy = [
    ["_build/host-deps/vc/bin/HostX64/x64/vcruntime*.*", "_build/$platform/release"],
]
link = []


########################################################################################################################
# Linux x86_64 platform:
########################################################################################################################

[linux-x86_64]
copy = []
link = []
